[package]
name = "Star-Shooter"
version = "0.1.0"
authors = ["Depressed Prick <subject@instance-3.local>"]
edition = "2018"

[dependencies]
amethyst = "0.15.2"
laminar = "0.4.0"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
